# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Portland Community of Mindful Living
email: info@mindful.community
description: "The Portland Community of Mindful Living practices meditation and mindfulness in the tradition of Zen Master Thich Nhat Hanh."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://portland.mindful.community" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
